meta_product_name: "Diginustrale"
meta_title: "Diginustrale - Les agriculteurs ont également besoin d'outils numériques"
meta_description: "Diginustrale permet aux éleveurs porcins de Corse de suivre leur l'élevage et leur production sur une plateforme unique, ainsi que de générer automatiquement des documents qu'ils devront fournir à l'organisme d'AOP."
meta_image: "background.jpg" # should exist in `app/assets/images/`
